# Generated by Django 3.2 on 2021-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='\\static\\image\\default_food.jpg', max_length=500),
        ),
    ]
